package abstractizareInterfata;

public interface AngajatInterface extends CommonInterface {

    //RECUNOASTEM INTR-UN FISIER JAVA O INTERFATA DUPA CUVANTUL INTERFACE
    //O INTERFATA CONTINE NUMAI METODE ABSTRACTE(METODE CARE NU AU BODY)
    //TOATE METODELE DINTR-O INTERFATA SUNT BY DEFAULT PUBLICE
    //INTR-O INTERFATA PUTEM AVEA ATAT METODE VOID, CAT SI METODE CU RETURN
    //O INTERFATA NU POATE CONTINE UN CONSTRUCTOR
    //DINTR-O INTERFATA NU PUTEM SA FACE UN OBIECT
    //O INTERFATA SE IMPLEMENTEAZA
    //CLASA CARE IMPLEMENTEAZA INTERFATA TREBUIE SA IMPLEMENTEZE TOATE METODELE ABSTRACTE DIN INTERFATA
    //O CLASA POATE IMPLEMENTA MAI MULTE INTERFETE
    //O INTERFATA POATE MOSTENI O ALTA INTERFATA


    void mergeLaServiciu();

    void desfasoaraActivitatea();

    void beaCafea();

    void incheieActivitatea();


}


