package accessControlPart1;

public class Caine {

    public void metodaPublica() {
    }

    private void metodaPrivata() {
    }

    protected void metodaProtected() {
    }

    void metodaDefault() {
    }
    //PUBLIC = ESTE UN TIP DE ACCESS CONTROL CE FACE PUBLICA INFORMATIA IN TOATE PACHETELE
    //PRIVATE = ESTE UN TIP DE ACCESS CONTROL CE FACE INFORMATIA PRIVATA IN CLASA CURENTA
    //DEFAULT = ESTE UN ALT TIP DE ACCESS CONTROL CE FACE VIZIBILA INFORMATIA DOAR IN PACHETUL RESPECTIV DACA VORBIM DE MOSTENIRE/CREEARE DE OBIECT
    //PROTECTED = ESTE UN TIP DE ACCESS CONTROL UNDE INFORMATIA ESTE PROTEJATA DOAR IN PACHETUL RESPECTIV DACA VORBIM DE MOSTENIRE/CREEARE DE OBIECT
    //DACA IESIM DIN PACHET VIZIBILITATEA LUI ESTE PREZENTA DOAR DACA VORBIM DE MOSTENIRE

}
